spring:
  profiles:
    active: dev
  config:
    location: classpath:/, classpath:/yamlFiles/

logging:
  level:
    net:
      engineeringdigest:
        journalApp: info

weather:
  api:
    key: ${WEATHER_API_KEY}
    string: ${WEATHER_API_STRING}