spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      user: ${SPRING_DATA_MONGODB_USER}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      # locally we don't have replicas which are required for Atomicity by @Transactional
      # it won't work with above database
      # but wrote only to do practice
  security:
    user:
      name: user
      password: pwd

server:
  port: 8080

# Set all variables (the variable names are correct based on your previous config)
#  export SPRING_DATA_MONGODB_HOST=localhost
#  export SPRING_DATA_MONGODB_PORT=27017
#  export SPRING_DATA_MONGODB_DATABASE=journalDB
#
#  export SPRING_DATA_MONGODB_USER=user_persona
#  export SPRING_DATA_MONGODB_PASSWORD=password_password_persona